name: ratyny
description: Ratyny - A community-based business rating platform.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^13.2.0
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
